apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vful90een-go
  janus-idp.io/tekton: vful90een-go
  backstage.io/kubernetes-id: vful90een-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vful90een-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
