apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vful90een-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vful90een-go 
  name: vful90een-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vful90een-go 
